Growthers/enshita

.github/workflows/fmt.yml
.github/workflows/lint.yml
.github/workflows/test.yml
front/src/index.html
front/yarn.lock

The script element is not a void element.
Refs: #36

fix(front): Fixed a bug that prevented Vite's HMR from working.

---

.github/workflows/token.yml

Maybe it works, no guarantee.
Refs: #39

fix(front): Fix CI

---

.github/workflows/token.yml

fix(front): Fix Actions trigger

---

.github/workflows/token.yml

I think, I hope it will move.
Refs: #39

fix(front): 人類は愚か、特にお前

---

.github/workflows/token.yml

I'm so 愚か human. Please f*ck me.
Refs: #39

fix(front): Fix args in CI

---

.github/workflows/fmt.yml
.github/workflows/lint.yml
.github/workflows/token.yml
front/package.json
front/src/styles/_variables.scss

- lint対象ファイルからscssを削除
- `fmt.yml` の実行をmainへのpushのときに変更
- add style lint to `lint.yml`
- コミットメッセージの頭文字を小文字に
- フォーマット
Refs: #50

fix(front): fix and update ci

---

.github/workflows/test.yml

remove comment out L25-L40 from `test.yml`
enable unit test and build storybook
Refs: #59

fix(front): remove comment out from test.yml

---

.github/workflows/test.yml
front/package.json

fix(front): fix ESLint target

---

front/package.json
front/src/libs/apiClient.ts
front/yarn.lock

feat(front): add axios

---

front/src/app.tsx
front/vite.config.ts

console.log(VITE_UNCHI) >> buriburi
Refs: https://github.com/Growthers/enshita/issues/97

fix(front): Changed envDir from process.cwd()/src to process.cwd()

---

renovate.json

fix: corrected automerge in renovate.json to true

---

front/package.json

```diff
- "lint:style": "stylelint ./src/styles/*.scss"
+ "lint:style": "stylelint ./src/styles/**/*.scss"
```
Refs #103

fix(front): fix style lint script

---

client/src/index.html
client/src/main.tsx

- #124 
クソデカcommitのサイト内で出ていたのコンソールエラー解決の`cherry-pick`です

feat(front): page console error

---

client/src/components/layout.tsx
client/src/stories/layout.stories.tsx
client/src/styles/layout.module.scss
client/src/tests/__snapshots__/layout.test.tsx.snap
client/src/tests/layout.test.tsx

- #34 
クソデカcommitの`layout`部分の`cherry-pick`です。

feat(front): layout

---

server/migrations/000001_initialize.up.sql

fix: DBマイグレーションスクリプトの構文エラーの修正

---

server/migrations/000002_add_event_enddate.down.sql
server/migrations/000002_add_event_enddate.up.sql

fix: eventに終了時間が含まれない問題の修正

---

server/migrations/000001_initialize.up.sql

fix: マイグレーションファイルのコメントがおかしい問題の修正

---

server/models/user.go

fix: change filename and structure name account to user

---

server/models/application.go
server/models/event.go
server/models/speakerquotatype.go
server/models/user.go

fix: remove json tags

---

server/models/speaker.go

feat: add speaker model

---

server/models/entities/application.go
server/models/entities/event.go
server/models/entities/speaker.go
server/models/entities/speakerquotatype.go
server/models/entities/user.go

fix: change directory

---

server/model/entity/application.go
server/model/entity/event.go
server/model/entity/speaker.go
server/model/entity/speakerquotatype.go
server/model/entity/user.go

fix: change directory name

---

server/model/entity/application.go
server/model/entity/event.go
server/model/entity/speaker.go
server/model/entity/speakerquotatype.go

fix: エンティティのリレーションがおかしい問題の修正

---

server/model/entity/layout.go

fix: consolidate directories

---

client/package.json
client/vitest.config.ts
client/yarn.lock

Refs: https://github.com/capricorn86/happy-dom/issues/494
Refs: #224

fix(front): Support for APIs not supported by happy-dom

---

server/model/domain/create_event_response.go
server/model/domain/event.go
server/model/domain/get_event_info_response.go
server/model/domain/get_event_list_response.go
server/model/domain/update_event_response.go

Close #178 
ref: https://laminne.stoplight.io/docs/enshita/fdd0662476899-
Close #183 
ref: https://laminne.stoplight.io/docs/enshita/910865a683539-
Close #184 
ref: https://laminne.stoplight.io/docs/enshita/713f840abc09e-
Close #185 
ref: https://laminne.stoplight.io/docs/enshita/e3d087ad2cfe1-

 add event response domain

---

server/model/entity/event.go

fix: event entity date

---

server/model/domain/get_form_response.go
server/model/entity/application.go

Close #227 
SQLはケースインセンシティブだから修正しなくていい　--- _laminne_

fix: fix spell

---

server/model/domain/verify_operator_registration_token_request.go

- close #207 
- https://laminne.stoplight.io/docs/enshita/0497619a61f61-

feat: add VerifyOperatorRegistrationTokenRequest entity

---

server/model/domain/create_breaktime_request.go

- close #220 
- https://laminne.stoplight.io/docs/enshita/d3d1c9a4e7b8f-

feat: add CreateBreaktimeRequest (domain)

---

server/model/domain/config_presentation_order_request.go

- close #218 
- https://laminne.stoplight.io/docs/enshita/bded28659388a-

feat: add ConfigPresentationOrderRequest entity

---

server/model/domain/submit_form_request.go

- close #215 
- https://laminne.stoplight.io/docs/enshita/74eb75f1d9781-

feat: add SubmitFormRequest entity

---

server/model/domain/create_operator_account_request.go

- close #206 
- https://laminne.stoplight.io/docs/enshita/b29b24d3ee22d-

feat: add CreateOperatorAccountRequest entity

---

server/model/domain/login_operator_and_admin_request.go

- close #210 
- https://laminne.stoplight.io/docs/enshita/1ffc9fbfb5d35-

feat: add LoginOperatorAndAdminRequest entity

---

server/model/domain/create_admin_request.go
server/model/domain/create_operator_request.go

- close #208 
- https://laminne.stoplight.io/docs/enshita/4d5652e2ed027-

feat: add CreateAdminRequest entity

---

server/model/entity/speaker.go

chore: add paragraph

---

.github/workflows/client-chromatic.yml
client/.gitignore
client/.storybook/main.js
client/package.json
client/yarn.lock

feat(front): Add jobs for publishing storybook

---

server/model/domain/create_admin_request.go
server/model/domain/create_form_request.go
server/model/domain/create_operator_account_request.go
server/model/domain/event_response.go
server/model/domain/form.go
server/model/domain/get_form_response.go
server/model/domain/image.go
server/model/domain/insert_form_request.go
server/model/domain/question.go
server/model/domain/send_form_request.go
server/model/domain/set_layout_config_request.go
server/model/domain/show_delivery_layout_response.go
server/model/domain/speaker_quota_type.go
server/model/domain/submit_form_request.go
server/model/domain/token.go
server/model/domain/update_form_info_request.go
server/model/domain/user.go
server/model/domain/verify_admin_registration_token_request.go
server/model/domain/verify_operator_registration_token_request.go
server/model/domain/websocketresponse.go

refactor model

---

.github/workflows/client-chromatic-test.yml
.github/workflows/client-chromatic.yml

ci(front): Fix Chromatic build directory

---

.github/workflows/client-chromatic-test.yml

ci(front): Fix regex

---

.github/workflows/client-chromatic-test.yml

fix(front): add TimeZone to client-chromatic-test ci

---

client/package.json
client/src/libs/apiClient.ts
client/src/libs/axios.ts
client/src/pages/event/index.tsx
client/src/pages/event/type/model.ts
client/src/routes.tsx
client/src/types/global-models.ts
client/vite.config.ts
client/yarn.lock

feat(front): Add SWR
